# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_app_url_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='pv',
            field=models.IntegerField(default=0, verbose_name='访问量'),
        ),
        migrations.AlterField(
            model_name='app',
            name='url_slug',
            field=models.CharField(db_index=True, max_length=100, verbose_name='URL'),
        ),
    ]
