# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20170825_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='readme_md',
            field=models.TextField(blank=True, null=True, verbose_name='markdown 描述'),
        ),
        migrations.AlterField(
            model_name='app',
            name='css_code',
            field=models.TextField(blank=True, null=True, verbose_name='CSS代码'),
        ),
        migrations.AlterField(
            model_name='app',
            name='html_code',
            field=models.TextField(blank=True, null=True, verbose_name='HTML代码'),
        ),
        migrations.AlterField(
            model_name='app',
            name='js_code',
            field=models.TextField(blank=True, null=True, verbose_name='JS代码'),
        ),
    ]
