# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-26 02:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_auto_20170825_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppTagShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=32, verbose_name='标签名称')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='app',
            options={'ordering': ('pri',)},
        ),
        migrations.AddField(
            model_name='app',
            name='pri',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='app',
            name='css_code',
            field=models.TextField(verbose_name='CSS代码'),
        ),
        migrations.AlterField(
            model_name='app',
            name='html_code',
            field=models.TextField(verbose_name='HTML代码'),
        ),
        migrations.AlterField(
            model_name='app',
            name='js_code',
            field=models.TextField(verbose_name='JS代码'),
        ),
        migrations.AddField(
            model_name='apptagship',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.App', verbose_name='应用'),
        ),
        migrations.AddField(
            model_name='apptagship',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Tag', verbose_name='标签'),
        ),
    ]
