# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-26 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_auto_20170826_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='css_code',
            field=models.TextField(blank=True, null=True, verbose_name='CSS代码'),
        ),
        migrations.AlterField(
            model_name='app',
            name='html_code',
            field=models.TextField(blank=True, null=True, verbose_name='HTML代码'),
        ),
        migrations.AlterField(
            model_name='app',
            name='js_code',
            field=models.TextField(blank=True, null=True, verbose_name='JS代码'),
        ),
    ]
