# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-26 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_auto_20170826_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='hot',
            field=models.BooleanField(default=True, help_text='初期热门就简单点来。', verbose_name='是否热门'),
        ),
    ]
