# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-29 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_tag_hot'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='是否有效'),
        ),
    ]
